[project]
name = "2025-claude-code-ida"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "jinja2>=3.1.6",
    "org-python>=0.3.2",
    "orgparse>=0.4.20251020",
    "uvicorn>=0.38.0",
]
